# Task: Push Door Right (CALVIN)
# @package _global_

task:
  name: door_right
  backend: calvin

main:
  instruction: "push the door to the right"

backend:
  calvin:
    target_behavior: move_slider_right
    scene_cfg:
      objects:
        fixed_objects:
          table:
            joints:
              base__slide: {initial_state: -0.28}

gemini_grounding:
  default_objects: [sliding door, door track]
